python E534_Higgs_Discovery_A.ipynb
python E534_Higgs_Discovery_A.py
python E534_Higgs_Discovery_B.ipynb
python E534_Higgs_Discovery_B.py
python E534_Higgs_Discovery_C.ipynb
python E534_Higgs_Discovery_C.py
python E534_Higgs_Discovery_D.ipynb
python E534_Higgs_Discovery_D.py
python example_mlp_mnist.ipynb
python google_colab_mnist_example.ipynb
python google_colab_mnist_example.py
python Makefile
python mlp_mnist.ipynb
python mlp-mnist.png
python mnist_autoencoder.ipynb
python mnist_autoencoder.py
python mnist_cnn.ipynb
python mnist_cnn.py
python mnist_lstm.ipynb
python mnist_lstm.py
python mnist_mlp_with_lstm.ipynb
python mnist_mlp_with_lstm.py
python mnist_rnn.ipynb
python mnist_rnn.py
python mnist_with_distributed_training.ipynb
python mnist_with_distributed_training.py
python mnist_with_pytorch.ipynb
python mnist_with_pytorch.py
python mnist_workflow.py
python python_warmup.ipynb
python python_warmup.py
python README.md
python requirements.txt
python run.sh
python tmp_E534_Higgs_Discovery_A.py
python tmp_E534_Higgs_Discovery_D.py
python tmp_mnist_mlp_with_lstm.py
